# Generated by Django 6.0.1 on 2026-01-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la rutina (ej: Push Day, Full Body A)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción o notas generales de la rutina')),
                ('is_active', models.BooleanField(default=False, help_text='Rutina actualmente en uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario propietario de esta rutina', on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rutina',
                'verbose_name_plural': 'rutinas',
                'db_table': 'routines',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de ejecución (0, 1, 2, ...)')),
                ('target_sets', models.PositiveIntegerField(default=3, help_text='Cantidad de series objetivo')),
                ('target_reps', models.PositiveIntegerField(default=10, help_text='Cantidad de repeticiones objetivo por serie')),
                ('notes', models.TextField(blank=True, default='', help_text="Notas (ej: 'Descanso 2 min', 'Tempo 3-0-1')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='exercises.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='routines.routine')),
            ],
            options={
                'verbose_name': 'ejercicio de rutina',
                'verbose_name_plural': 'ejercicios de rutina',
                'db_table': 'routine_exercises',
                'ordering': ['routine', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'is_active'], name='routines_user_id_981748_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', '-updated_at'], name='routines_user_id_ed268f_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexercise',
            index=models.Index(fields=['routine', 'order'], name='routine_exe_routine_3b89ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routineexercise',
            unique_together={('routine', 'exercise')},
        ),
    ]
