# Generated by Django 6.0.1 on 2026-01-12 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Fecha del workout')),
                ('start_time', models.DateTimeField(blank=True, help_text='Hora de inicio del workout', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Hora de finalización del workout', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notas generales del entrenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(blank=True, help_text='Rutina base (opcional, puede ser None para freestyle)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='routines.routine')),
                ('user', models.ForeignKey(help_text='Usuario que realizó el workout', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrenamiento',
                'verbose_name_plural': 'entrenamientos',
                'db_table': 'workouts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en que se realizó el ejercicio')),
                ('notes', models.TextField(blank=True, default='', help_text="Notas del día (ej: 'Sentí dolor en el hombro')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'ejercicio de entrenamiento',
                'verbose_name_plural': 'ejercicios de entrenamiento',
                'db_table': 'workout_exercises',
                'ordering': ['workout', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(help_text='Número de serie dentro del ejercicio')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso utilizado en kg (null para ejercicios de peso corporal)', max_digits=6, null=True)),
                ('reps', models.PositiveIntegerField(help_text='Repeticiones realizadas')),
                ('completed', models.BooleanField(default=True, help_text='Si la serie se completó exitosamente (False si falló)')),
                ('rpe', models.PositiveIntegerField(blank=True, help_text='Esfuerzo percibido (1=muy fácil, 10=fallo muscular)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
                'db_table': 'sets',
                'ordering': ['workout_exercise', 'set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', '-date'], name='workouts_user_id_569378_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['routine'], name='workouts_routine_265357_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['-date'], name='workouts_date_ac2ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['workout', 'order'], name='workout_exe_workout_9a1a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['exercise'], name='workout_exe_exercis_6bfd73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutexercise',
            unique_together={('workout', 'exercise')},
        ),
        migrations.AddIndex(
            model_name='set',
            index=models.Index(fields=['workout_exercise', 'set_number'], name='sets_workout_7f4411_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('workout_exercise', 'set_number')},
        ),
    ]
