# Generated by Django 6.0.1 on 2026-01-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del ejercicio (ej: Bench Press)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción o instrucciones del ejercicio')),
                ('muscle_group', models.CharField(choices=[('chest', 'Pecho'), ('back', 'Espalda'), ('legs', 'Piernas'), ('shoulders', 'Hombros'), ('arms', 'Brazos'), ('core', 'Core'), ('cardio', 'Cardio'), ('other', 'Otro')], help_text='Grupo muscular principal', max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='Si es True, el ejercicio es visible para todos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio (None si es global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'db_table': 'exercises',
                'ordering': ['muscle_group', 'name'],
                'indexes': [models.Index(fields=['is_global', 'muscle_group'], name='exercises_is_glob_45aac0_idx'), models.Index(fields=['created_by'], name='exercises_created_eae801_idx')],
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
